@startuml

package api {
    class 飲み会Request {
        - String 開催名
        - String 開催日時
        - String[] 参加氏名[n]
        - String[] 幹事区分[n]
        - String[] 支払区分[n]
        - String 請求金額
        + 飲み会情報 create()
    }
}

package domain {
    class 飲み会情報 {
    }
    package 開催情報 {
        class 開催名 {
        }
        class 開催日時 {
        }
    }

    package 参加者 {

        class 参加者リスト {
            - List<参加者>
        }
        class 参加者 {
        }
        class 参加者名 {
        }
        enum 幹事区分 {
            幹事
            幹事以外
        }

        参加者リスト "1" --> "n" 参加者
        参加者 --> 参加者名
        参加者 --> 幹事区分
    }

    package 支払 {
        enum 支払区分 {
            多め
            普通
            少なめ
        }
        class 支払割合 {
        }

        支払区分 --> 支払割合
    }

    package 金額 {
        class 合計支払金額 {
        }
        class 参加者ごとの支払金額リスト {
            - List<参加者ごとの支払金額>
            + 合計支払金額 合計支払金額を計算する()
        }
        class 参加者ごとの支払金額 {
        }
        class 請求金額 {
            + 参加者ごとの支払金額 参加者ごとの支払金額を計算する(参加者リスト, 支払区分)
        }
        class 差額 {
        }
        差額 --> 合計支払金額
        差額 --> 請求金額
        請求金額 --> 参加者ごとの支払金額
        参加者ごとの支払金額リスト "1" --> "n" 参加者ごとの支払金額
        参加者ごとの支払金額リスト --> 合計支払金額
    }

    参加者 --> 支払区分
    飲み会情報 --> 開催名
    飲み会情報 --> 開催日時
    飲み会情報 --> 参加者リスト
    飲み会情報 --> 請求金額
    請求金額 --> 参加者リスト
    請求金額 --> 支払区分
}

飲み会Request -> 飲み会情報

@enduml