@startuml

package domain {
    class 飲み会 {
        - 飲み会名
        - 開催日時
        - 参加者一覧
        - 請求金額
    }

    class 参加者ごとの支払金額 {
        List<一人あたりの支払金額>
    }


    参加者ごとの支払金額 --> 一人あたりの支払金額
    一人あたりの支払金額 --> 一人あたりの支払割合
    一人あたりの支払金額 --> 請求金額

    一人あたりの支払割合 --> 比率
    一人あたりの支払割合 --> 支払区分ごとの人数

    比率 --> 割合
    比率 --> 支払区分ごとの人数

    割合 --> 支払区分

    支払区分ごとの人数 --> 参加者一覧
    支払区分ごとの人数 --> 支払区分
}

@enduml