@startuml
/'

## f1の実装
参加者ごとの支払金額　f1(参加者一覧、請求金額) {
   return 割り勘金額(人数計算(参加者一覧)、請求金額);
}

## １番外のメソッド
INパラ	参加者一覧、請求金額
OUTパラ	参加者ごとの支払金額
メソッド形式	参加者ごとの支払金額　f1(参加者一覧、請求金額)

## 参加者ごとの支払金額を算出するメソッド
INパラ	参加者人数、請求金額
OUTパラ	参加者ごとの支払金額
メソッド形式	参加者ごとの支払金額　割り勘金額(参加者人数、請求金額)

## 参加者人数を算出するメソッド
INパラ	参加者一覧
OUTパラ	参加者人数
メソッド形式	参加者人数　人数計算(参加者一覧)

## 支払区分ごとの人数を算出するメソッド
INパラ	参加者一覧、支払区分
OUTパラ	支払区分ごとの人数
メソッド形式	支払区分ごとの人数　支払区分ごとの人数算出(参加者一覧、支払区分)

/* 20200113 追記 */
## 支払区分ごとの比率を算出するメソッド
INパラ　支払区分ごとの比重
OUTパラ　支払区分ごとの比率
メソッド形式　支払区分ごとの比率　比率算出(支払区分ごとの比重)

/* 20200113 追記 */
## 支払区分ごとの比重算出するメソッド
INパラ　支払区分、支払区分ごとの人数
OUTパラ　支払区分ごとの比重
メソッド形式  支払区分ごとの比重　支払区分ごとの比重算出(支払区分、支払区分ごとの人数)

## 一人当たりの比率を算出するメソッド
INパラ　比率、支払区分ごとの人数
OUTパラ　一人当たりの比率
メソッド形式　一人当たりの比率　一人当たりの比率を算出(比率、支払区分ごとの人数)

## 一人当たりの支払金額を算出するメソッド
INパラ　請求金額、一人当たりの比率
OUTパラ　一人当たりの支払金額
メソッド形式　一人当たりの支払金額　一人当たりの支払金額を算出(請求金額、一人当たりの比率)
'/

class 飲み会 {
    + 参加者ごとの支払金額　f1(参加者一覧、請求金額)
}

package member {
    class 参加者一覧 {
        - List<参加者>
        + 参加者人数　人数計算(参加者一覧)
    }

    class 参加者 {
        - 支払区分
    }
    class 支払区分 {
        - 普通（1）
    }
    class 参加者人数 {
        - int
    }
}

package 計算 {
    class 参加者ごとの支払金額 {
        + 参加者ごとの支払金額　割り勘金額(参加者人数、請求金額)
    }

    class 支払区分ごとの人数 {
        + 支払区分ごとの人数　支払区分ごとの人数算出(参加者一覧、支払区分)
    }

    class 請求金額 {
        - int
    }

    class 支払区分ごとの比率 #skyblue {
        + 支払区分ごとの比率　比率算出(支払区分ごとの比重)
    }

    class 一人当たりの比率 {
        + 一人当たりの比率　一人当たりの比率を算出(比率、支払区分ごとの人数)
    }

    class 一人当たりの支払金額 {
        　+ 一人当たりの支払金額　一人当たりの支払金額を算出(請求金額、一人当たりの比率)
    }

    class 支払区分ごとの比重 #skyblue {
        + 支払区分ごとの比重　比重算出(支払区分, 支払区分ごとの人数)
    }
}

飲み会 -d-> 参加者ごとの支払金額
飲み会 -d-> 請求金額
飲み会 -d-> 参加者一覧
参加者ごとの支払金額 -d-> 参加者人数
参加者ごとの支払金額 -d-> 請求金額
参加者一覧 -d-> 参加者人数
参加者一覧 -d-> 参加者
参加者 -d-> 支払区分
支払区分ごとの人数 -d-> 参加者一覧
支払区分ごとの人数 -d-> 支払区分
支払区分ごとの比率 -d-> 支払区分ごとの比重 #skyblue
一人当たりの比率 -d-> 支払区分ごとの比率
一人当たりの比率 -d-> 支払区分ごとの人数
一人当たりの支払金額 -d-> 請求金額
一人当たりの支払金額 -d-> 一人当たりの比率
支払区分ごとの比重 -d-> 支払区分 #skyblue
支払区分ごとの比重 -d-> 支払区分ごとの人数 #skyblue

@enduml