@startuml
title ユースケース図
skinparam packageStyle rect
left to right direction

actor :幹事:
actor :システム:

幹事 -- (飲み会 を開催する)

rectangle 割り勘システム {
  幹事 -- (開催した 飲み会 の 名前, 開催日時 などを設定する)
  幹事 -- (開催した 飲み会 の 参加者 を追加/削除する)
  幹事 -- (開催した 飲み会 の 支払区分ごとに 支払割合 を設定する)
  幹事 -- (開催した 飲み会 の 請求金額 を設定する)
  システム -u- (飲み会 の 参加者ごとの支払金額 を計算する)
}

/' ユースケースのソート '/
(飲み会 を開催する) -[hidden]l- 割り勘システム
(開催した 飲み会 の 名前, 開催日時 などを設定する) -[hidden]l- (開催した 飲み会 の 参加者 を追加/削除する)
(開催した 飲み会 の 参加者 を追加/削除する) -[hidden]l- (開催した 飲み会 の 支払区分ごとに 支払割合 を設定する)
(開催した 飲み会 の 支払区分ごとに 支払割合 を設定する) -[hidden]l- (開催した 飲み会 の 請求金額 を設定する)
(開催した 飲み会 の 請求金額 を設定する) -[hidden]l- (飲み会 の 参加者ごとの支払金額 を計算する)

@enduml